// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPtgNIRfGOdj8hb6eXRVC6ymyL4SFzPh8',
    appId: '1:76625693704:web:dbb8a8810cfbb049c995bd',
    messagingSenderId: '76625693704',
    projectId: 'mazproject-6c5d6',
    authDomain: 'mazproject-6c5d6.firebaseapp.com',
    storageBucket: 'mazproject-6c5d6.firebasestorage.app',
    measurementId: 'G-ZFFY4CRQ5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBqMgsJTzQOPROwgQgipQeiTYeih63gHw',
    appId: '1:76625693704:android:7a58201416601330c995bd',
    messagingSenderId: '76625693704',
    projectId: 'mazproject-6c5d6',
    storageBucket: 'mazproject-6c5d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_m5nfaYHaExrsuA34IjNzKbT-XGdpf64',
    appId: '1:76625693704:ios:1813b59b2d37341ec995bd',
    messagingSenderId: '76625693704',
    projectId: 'mazproject-6c5d6',
    storageBucket: 'mazproject-6c5d6.firebasestorage.app',
    iosBundleId: 'com.example.madPro',
  );
}
